### ISSUE TITLE
Many (all?) core packages show "No README"

### ISSUE THREAD

**Issue by rsese** [atom/settings-view#1069]
_From @jaller94 on August 3, 2018 5:29_

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![The settings page of the about package says No README](https://user-images.githubusercontent.com/10872136/43625720-5856ef06-96a3-11e8-96ee-d97b17177b21.png)

### Steps to Reproduce

1. Go into the packages settings
2. Search and select the about package

**Expected behavior:** The Readme shows a description of the package’s use. Most likely the text would be the same text as this repository’s README.md.

**Actual behavior:** It says "No README"

**Reproduces how often:** every time

### Versions

Atom 1.28.0 on Linux_x64
Atom 1.29.0 on MacOS

_Copied from original issue: atom/about#85_

**Comment by rsese** [comment]
Thanks for the report @jaller94 - I noticed this was the case with other packages besides atom/about (e.g. archive-view, autocomplete-atom-api, autocomplete-css).

Reproduced on macOS 10.12.6 with 1.31.0-nightly0.

**Comment by jaller94** [comment]
Do they all start with the letter a? 😅

**Comment by jaller94** [comment]
Also affected: autoflow, autosave
I think I found a rule.. 😉

**Comment by rsese** [comment]
lol 😄 No it looks like all the ones I've checked so far are showing the same thing including github and tabs for example, so not just `a` packages.

**Comment by daviwil** [comment]
I tried a series of old Atom releases and this problem seems to have occurred between Atom 1.20.1 and 1.21.0.  Looking at the [release notes for 1.21.0](https://github.com/atom/atom/releases/tag/v1.21.0), it seems that there are two changes that are possible culprits:

- [atom/atom#14682 - Bring back ASAR archives](https://github.com/atom/atom/pull/14682): Is it possible that bringing back the ASAR file caused issues for [normalize-package-data](https://github.com/npm/normalize-package-data)?
- [atom/atom#15522 - Convert package-manager from Coffeescript to JavaScript](https://github.com/atom/atom/pull/15522): Converting to JavaScript might have introduced regressions in the code that reads package metadata

I'll continue looking for the root cause.

**Comment by daviwil** [comment]
@annthurium and I investigated this further and discovered that the re-introduction of ASAR archiving was indeed the culprit.  It turns out that we've been excluding Markdown files from the ASAR package which meant that the Settings view could never find README.md files for bundled core packages.  PR incoming.
