### ISSUE TITLE
C:\Users\UDIT is not recognised as internal or external command shown on command line of atom text editor

### ISSUE THREAD

**Issue by deoudit** [atom/settings-view#1073]
When I run c and c++ then on output screen this error is generated

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]
C:\Users\UDIT is not recognised as internal or external command shown on cmd of atom
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Aerijo** [comment]
Hi @deoudit :wave:

Could you please provide steps to reproduce this error? This part in particular, because Atom doesn't have a command line built into it.
> shown on command line of atom text editor


It may be that you're using a community package, in which case you should raise the issue on their repo.

(regarding the issue itself, you likely have a space or other special character in your username, which caused the rest of the path to be ignored)

**Comment by deoudit** [comment]
When I run my c and c++ in atom then on output screen this message occurs
without showing the output

uditdeo

**Comment by rsese** [comment]
Thanks for clarifying - since this isn't an issue with this repository and it's an issue with a community package, you should open an issue with the maintainers of the package you're using or you can ask for help on the official message board:

https://discuss.atom.io/

The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
