### ISSUE TITLE
array类型无法使用逗号

### ISSUE THREAD

**Issue by 233cy** [atom/settings-view#1099]
array类型无法使用逗号

**Comment by 233cy** [comment]
![default](https://user-images.githubusercontent.com/29916783/51633885-b63fe000-1f8d-11e9-97ce-58eb0042a495.png)
array类型中无法使用逗号十个问题

**Comment by 233cy** [comment]
@defunkt @technoweenie @Caged @jnewland

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Also, please be sure you're reporting on the correct repository - for example, if you're reporting a problem with JavaScript syntax highlighting, then you can open an issue in https://github.com/atom/language-javascript.

Lastly, the Atom maintainers will take a look as soon as they can, no need to @ mention people.

Thanks for understanding and meeting us half way :grinning:
