### ISSUE TITLE
Jumpy cursor in `string`/`array` inputs

### ISSUE THREAD

**Issue by pfitzseb** [atom/settings-view#1117]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Typing in a config entry of type `string` or `array` sometimes causes the cursor to jump to the end of the input and the last typed characters to repeatedly disappear and appear again.

In the following gif I just type and don't move the cursor manually at all:

![peek 2019-02-26 09-49](https://user-images.githubusercontent.com/6735977/53399841-fdfec080-39ac-11e9-86a2-ccfea452bfd6.gif)

I can still repro this in safe mode, but it seems to happen much less frequently.

### Steps to Reproduce

1. Open Editor/package settings.
2. Type in `string` or `array` config in the middle of a word.

**Expected behavior:** Normal input behaviour.
**Actual behavior:** Cursor jumps to end of input, char that was input last disappears and appears again.
**Reproduces how often:** 1 out of 10 times in safe mode, maybe? More often with packages loaded.

### Versions

```
λ atom --version
Atom    : 1.34.0
Electron: 3.1.4
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
```
λ apm --version 
apm  2.1.3
npm  6.8.0
node 11.10.0 x64
atom 1.34.0
python 2.7.15
git 2.20.1
```
```
λ cat /etc/lsb-release              
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.3
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"
```

**Comment by rsese** [comment]
Thanks for the report!

> Atom    : 1.34.0
> Electron: 3.1.4

Based on these versions, it looks like you're using an unofficial build or distribution of Atom (the official stable 1.34.0 release ships with Electron 2.0.16).  Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
