### ISSUE TITLE
Can not Install ANY  Package!

### ISSUE THREAD

**Issue by Ahmedmuhammed** [atom/settings-view#1124]
[Description of the issue]

When I trying Install Eslint Package I am getting This Error:
"npm ERR! Unexpected end of JSON input while parsing near '...dencies":{"ansi-sty

- I had tried this command in terminal: npm cache clean --force, But it did not solve the problem.

### Versions

atom version: 1.35.1
npm version: 6.9.0.
machine: Windows 7 (64bit).

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Which specific package are you trying to install?  https://atom.io/packages/linter-eslint?

And just to clarify, do you have trouble trying to install other packages as well?  Do you see the same/similar error if you try to install https://atom.io/packages/zen?

Have you tried deleting `~\.atom\.apm`?
