### ISSUE TITLE
Uncaught Error: Tried to unload active package 'atom-ide-terminal'

### ISSUE THREAD

**Issue by APakrohk** [atom/settings-view#1131]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.1 x64
**Electron**: 4.1.4
**OS**: linux 5.1.9-arch1-1-ARCH
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.261.3

### Stack Trace

Uncaught Error: Tried to unload active package 'atom-ide-terminal'

```
At /usr/lib/atom/src/package-manager.js:637

Error: Tried to unload active package 'atom-ide-terminal'
    at PackageManager.unloadPackage (/usr/lib/atom/src/package-manager.js:637:13)
    at PackageManager.module.exports.PackageManager.unload (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:444:30)
    at PackageManager.module.exports.PackageManager.install (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:454:12)
    at PackageCard.install (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:826:27)
    at HTMLButtonElement.installButtonClickHandler (/usr/lib/atom/node_modules/settings-view/lib/package-card.js:289:16)
```

### Commands

```
     -3:36.1.0 settings-view:install-packages-and-themes (input.hidden-input)
```

### Non-Core Packages

```
atom-dracula-syntax 2.3.0 
atom-ide-datatip 0.0.0 
atom-ide-debugger-node 0.7.3 
atom-ide-markdown-service 1.2.0 
atom-ide-ui 0.13.0 
dracula-syntax 2.0.7 
dracula-ui 0.6.0 
file-icons 2.1.33 
icon-fonts 3.1.5 
ide-python 1.4.1 
unleash-django 1.3.2 
```

`Error starting process:
Error: Cannot find module '/home/ali/.atom/packages/atom-ide-ui/node_modules/nuclide-prebuilt-libs/pty/build/pty-node-v69-linux-x64/pty.node'`

**Comment by rsese** [comment]
Thanks for the report!

> Atom: 1.38.1 x64
< Electron: 4.1.4

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please, you can subscribe to https://github.com/atom/atom/issues/16873 if you'd like.

**Comment by APakrohk** [comment]
I used the official repository of ArchLinux :
https://wiki.archlinux.org/index.php/Official_Repositories

**Comment by Aerijo** [comment]
@APakrohk That is not an official (i.e., maintained by the Atom team) repository.
