### ISSUE TITLE
Support trackpad swipe gestures within settings view

### ISSUE THREAD

**Issue by swrobel** [atom/settings-view#1133]
## Summary

1. `⌘,` (open settings)
2. Click 'Packages'
3. Click a specific package
4.  Swipe left-to-right

You are now on 'Packages'

<img width="361" alt="Screen Shot 2019-07-26 at 12 47 16 PM" src="https://user-images.githubusercontent.com/157270/61977700-ff580780-afa3-11e9-979e-d9368dd7368b.png">

This should work similarly on 'Themes' and 'Install'

## Motivation

This is typical functionality on other Macs where you navigate nested panes. I know this may seem trivial, but I find myself doing this all the time when browsing packages/themes and find myself surprised every time when it doesn't work.

## Describe alternatives you've considered

Back keyboard shortcuts would also be something to consider, though I'm not proposing them here.

## Additional context

Similar request a long time ago in the core atom project https://github.com/atom/atom/issues/2060

[Electron feature ref](https://electronjs.org/docs/api/browser-window#event-swipe-macos)

**Comment by rsese** [comment]
Thanks for the suggestion :+1:  Though I can see how swipe support would be a nice plus, as mentioned in the issue template we're unlikely to prioritize feature requests right now.  So we'll close this out since it's not something that would be worked on, but I'll let the other maintainers know that this is something that you'd like to see and would help your workflow.
