### ISSUE TITLE
Can't install packages or themes in atom

### ISSUE THREAD

**Issue by Sebastian1811** [atom/settings-view#1134]
Hello, I recently installed Atom on my  PC and I am having this error when I go to settings > packages:

Fetching featured packages failed.
It does not want to load the features packages, and searching for packages does not do anything.

I have the last version of atom 1.39
![err](https://user-images.githubusercontent.com/53380760/61998922-8aa4cc00-b07c-11e9-8122-7a51b9f810c5.png)

**Comment by Sebastian1811** [comment]
I even tried some solutions posted in different issues but it didn't work, Can somebody help me

**Comment by rsese** [comment]
Thanks for the report - based on the error, this seems like a local system issue where `cmd.exe` can't be found on your system/path?  Looks like this has come up before on the message board: https://discuss.atom.io/search?q=cmd.exe%20enoent%20order%3Alatest.

Not sure what you've tried but I'd suggest posting on the message board and detail exactly what you tried.  There are a number of helpful community members that should be able to point you in the right direction.

Going to close this out since it doesn't sound like an Atom issue but we can always reopen if necessary.
