### ISSUE TITLE
Checkbox to remove 'unset!' from list of keybindings

### ISSUE THREAD

**Issue by thiagola92** [atom/settings-view#1135]
## Summary

One checkbox to remove 'unset!' keybindings from the list of keybindings.

## Motivation

I use my own keybindings for everything and i remove keybindings that i don't use.  
I don't like to see keybindings that i disabled in the settings.

## Additional context

Look at the list size  
![unset](https://user-images.githubusercontent.com/9352894/62827292-8ad7b800-bba2-11e9-9746-33c50beca6aa.gif)

**Comment by rsese** [comment]
Thanks for the suggestion!

A similar issue was opened for this so we'll close in favor of that one if you want to subscribe: https://github.com/atom/settings-view/issues/143

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
