### ISSUE TITLE
Defaults should be editable

### ISSUE THREAD

**Issue by seth--** [atom/settings-view#243]
Just installed atom. Being a python developer I wanted to hide *.pyc from tree view, but I also wanted to maintain the default ignored names. The problem is ".git, .hg, .svn, .DS_Store, Thumbs.db" dissapears when the textbox is clicked, and the user has to type it all again

**Comment by surdu** [comment]
I second this. In my package, if the user wants to change the defaults for my setting, it will have to re-type all the defaults, because otherwise they're lost:

![image](https://cloud.githubusercontent.com/assets/11520795/6993055/4c75add4-daf0-11e4-9bdc-a26b561d5d26.png)

**Comment by miloszw** [comment]
:+1:
any updates on this?

**Comment by dubbleb** [comment]
came with the same complaint as found in https://discuss.atom.io/t/append-to-default-nonwordcharacters-in-settings/11590/4 - which led me here, and seems to be the right way to approach this, pretty simple.

I think this especially applies to the non-word chars box since that's basically a collection of the hardest to find and type keys on the keyboard

**Comment by mjrk** [comment]
+1

**Comment by evjan** [comment]
I had the idea of binding to an "focus" event or something like that and when an empty textbox is focused on it puts in the default values. However, I can't find any event that seems to work like that in the [API docs](https://atom.io/docs/api/v1.1.0/TextEditor). I tried the different cursor ones, e.g. onDidAddCursor, but that didn't seem to fire when I clicked the input. 

Ideas?

**Comment by mjrk** [comment]
How about right-click "Insert defaults"?

**Comment by evjan** [comment]
That could work! Would it be clear enough? Would people try right-clicking when the defaults disappear after clicking in the box?

**Comment by surdu** [comment]
Why not just have the defaults always there ? That IS the definition of "default": "a preselected option adopted by a computer program or other mechanism when no alternative is specified by the user".

For now, you set the default to "something" but the computer says: "neaaaah, I'll just leave this blank"

So why come with twisted,  non-intuitive solutions to a straight forward problem ?

**Comment by mjrk** [comment]
IMHO right-click "Insert defaults" would be clear enough. It was the first thing I was looking for. Even if there is another great solution, the context menu basic functionality would not harm / could live next to any more complex GUI solution.

@surdu it depends on the context. In general, defaults help to decrease the configuration burden and I like the way the are visible in atom right now. I see them and they don't distract. They are updated automatically on version updates because they are not just there.
Important: If defaults are always there, the user would need a "Reset defaults" context menu entry and ideally some feedback whether he actually changed defaults etc.

**Comment by surdu** [comment]
To reset to defaults all you need is a button on the bottom of the Settings group that resets the settings to default, like most editors / applications. 

Really, this is a solved problem for a while now ...

**Comment by mjrk** [comment]
I got your point. 

Still, I like it more how it is right now in atom and IMHO the context menu should always be there. So, "Putting custom context menus on text inputs sounds as an unintuitive, unnecessary over-complication" - I have another opinion regarding this matter.

My firefox' about:config makes all entries "bold" if I changed it manually. I can right-click "Reset". I think this is cool and helps me a lot. SO, IMHO all kind of property views chould provide feedback about default/modified and give the possibility to append/reset single entries to their default value.
