### ISSUE TITLE
Centered layout is awkward on wide displays

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#318]
I love what you've all been doing with the Settings UI so far! But I did notice that the new centered single column looks a little awkward on wide displays:

![screenshot from 2015-01-08 09 39 16](https://cloud.githubusercontent.com/assets/823545/5664131/e9a5bb94-971b-11e4-8efb-1ba143e39758.png)
![screenshot from 2015-01-08 09 38 35](https://cloud.githubusercontent.com/assets/823545/5664003/a42146b6-971a-11e4-911d-421f518f3356.png)

It seems like it might work better with multiple columns to better take advantage of all that negative space?

**Comment by postcasio** [comment]
Yeah, it looks even more awkward on a 2560x1440 display. I added this to my stylesheet to get it into two columns, and a little wider:

```less
.settings-view {
	.section-container {
		max-width: 50%;
	}
	.package-container .row {
		width: 50%;
		float: left;
		padding: 0 0 0 (@component-padding / 2);
		&:nth-child(2n+1) {
			clear: both;
			padding: 0 (@component-padding / 2) 0 0;
		}
	}
}
```

**Comment by philipgiuliani** [comment]
I also noticed this today. I would like to have it left-aligned and not centered.

**Comment by thedaniel** [comment]
For right now, centering is a good compromise for varying window sizes IMO, but this could definitely be better. 

I am strongly :-1: on multiple columns. I had multiple columns in the original prototype for this, but removed them because they make lists of related content difficult to scan quickly, which I think is the most important usage pattern of this view.

**Comment by thedaniel** [comment]
I'm not going to stand in the way of a nice left-aligned list though if someone can come up with one :)

**Comment by mnquintana** [comment]
@thedaniel I'm not so convinced that multiple columns would make it too difficult to scan content (for the Packages pane anyway), as long as the columns are kept to a reasonable number (ie. 2 or 3). I actually found the previous incarnation of settings more readable because with the 2 column layout scanning packages (in the Featured section anyway) didn't entail having to scroll forever.

**Comment by simurai** [comment]
Ya, I agree it looks a bit odd on very large screens. Personally I find it less problematic because I either have 2 panes open or two windows side by side. But could be just me.

Re __grids__: [List Beats Grid: Linear Feeds Perform Two to Three Times Better Than Grids](http://blog.getprismatic.com/list-beats-grid-linear-feeds-perform-two-to-three-times-better-than-grids-2/) But to be fair, you probably will find posts that are pro grids. :wink: I think it's like this: If you __actively__ try to find something, scanning down a list is easier. No zig-zag. If you just __browse__ around, a grid is nice. Like on Pinterest or photo galleries. Something might be worth a try: Still keep each package "card" in a list, but have the Community, Core and Dev list as 3 columns next to each other. More like a table.

__Left aligned__: Ya, would be another option. Keep it centered, but when it starts to look odd, like at 1500px, switch to left aligned.

__As modal__: There were discussions to move the settings out of the tabs and show them as modal. It would also solve the problem that the settings get too squeezed on a smaller screen with multiple panes open.

**Comment by mnquintana** [comment]
@simurai –

Re: modal – I kinda like this idea (I remember remarking at how slick Brackets' Extensions modal was), but there are some advantages to keeping it a tab, namely, using it in a pane while you have something else open in another pane. (e.g. Imagine if you're setting up a whole bunch of keybindings in your keymap at once – it's pretty nice that you can have Settings open in a panel and just go down the list copying over default keybindings and changing them in your file). Another disadvantage of a modal is that it would necessarily need to be smaller than the open Atom window, which means you would be seeing a lot fewer packages at once before needing to scroll.

Re: grids – I'm basically with you – I agree that if you're actively looking for something, it's easier to scan down a list, but that grids are nicer for browsing. I think that 3 column "table" idea is definitely worth trying – one of the current issues with the list layout IMO is that it's impossible to tell where each of the other 2 categories begin, which for me leads to a lot of scrolling down, and a lot of backtracking, to try to figure out where Core Packages starts, for instance. (To be fair, if you only had like, 4 community packages installed I guess it wouldn't be much of an issue :stuck_out_tongue_closed_eyes:) At the very least, if the current layout stays the same, I think there should be some nav links or something to jump to each category of package (but this is probably a topic for another issue).

Re: left-aligned: How bad does it look left aligned at every device width?

**Comment by simurai** [comment]
#### Modal

> using it in a pane while you have something else open in another pane.

Yess.. I also like having the settings in a split pane and see how changes affect the editor. It doesn't have to be a "traditional" modal that sits in the middle, it could be more like a "side panel" sliding in from the right. Something like this: 

![modal](https://cloud.githubusercontent.com/assets/378023/5715037/e0207d5e-9b15-11e4-9962-0fd2c5620b09.png)

So the settings would be on top, have a fixed width, still full height and anchored to the right. Some pro's:

* You can still make changes in the settings and see the editor at the same time. On very small screens it would cover most of the editor, but the important part like indent guide is on the left. And you could close the tree-view to get a bit extra space.
* Less hassle to move the settings into a new split pane, since it already is kinda like a split pane on the right.
* Fixed width makes it easier to design, no odd looking if either the tab is too large or too narrow
* Since it's based on the whole viewport, it could even use media queries to adapt to window size
* The settings wouldn't be forced to adapt to themes. The non-themed settings looked odd when in a tab, but as a side panel it's more its own thing and can be different from the rest. It also wouldn't need to make compromises so it looks okayish in most themes. And theme creators wouldn't have to bother about styling the settings, although they still could override it.. would be an opt-in.

Cons:

* Keybindings.. Everything could be quite narrow except the keybindings that are best viewed with a large width. Not sure.. either make the panel expand more, or move it out of the settings menu to *somewhere*.

Anyways.. changing to a modal/side panel isn't just a quick fix.. so in the meantime:

#### Grids

Right, if there are lots of packages, it's easy to shoot past the next category. Sub nav might be an option or make the headers/titles "sticky". So when scrolling they would stick to the top until the next category is reached. Then you always see where you are. Plus maybe make categories collapsable?

#### Left aligned

> How bad does it look left aligned at every device width?

Not terribly bad.. we can change it to left aligned for now. For those that "really" prefer center aligned can always change it in their `styles.less`.

**Comment by thedaniel** [comment]
**re: short term changes**

> > How bad does it look left aligned at every device width?
> Not terribly bad..

I think we shouldn't go for "least bad", we should go for "good" and degrade to "acceptable" in less common cases ;)

> or make the headers/titles "sticky"

This seems like an easy win.

**long term changes**

I do very much like the idea of a fixed width overlapping panel (so not technically a modal since you can still interact with most of the editor) but I think that it's probably not super high priority for right now since we just moved the settings UI forward. I think we should pick up as many quick wins as we can as "post-:ship: care" and come back to settings-view in the future, and take time to do some research / prototyping etc. then.

**Comment by simurai** [comment]
> degrade to "acceptable" in less common cases

Yeah, it's just not that easy to tell the "less common cases". Or how most people use Atom. Personally, I either have 2 panes (split) or 2 narrower windows (side by side) open, so the centering wasn't really an issue. But if most people use a large pane, then left-aligned would be the better default. I wonder if Atom's stats could give some clue about it.

Anyways, it's now left aligned by default. In case, here a snippet for your `styles.less` to make it centered again: 

```less
// center settings
.settings-view .section-container {
  margin: 0 auto;
}
```

Ok, I'll close this for now and make a new issue about the "sticky" header. And we can keep the "settings in a side panel" for some day in the future.

**Comment by thedaniel** [comment]
> Yeah, it's just not that easy to tell the "less common cases"

![screen shot 2015-01-13 at 8 49 08 pm](https://cloud.githubusercontent.com/assets/1476/5734215/b48d2e4e-9b65-11e4-8dd7-864a75c53288.png)

**Comment by simurai** [comment]
@thedaniel Thanks.. ok, so arguably centered looks good up until `1440`. Which means that 40.94% potentially see it in an odd way. But that number probably goes down since split panes and resized windows are not considered.

Anyways, I feel like still leaving it left-aligned. A potential of 20%-30% seeing it __oddly__, might still be more "harm", than 70%-80% seeing it _ok-ish_.

**Comment by thedaniel** [comment]
totally, i wasn't trying to "gotcha" with that, just posted in a hurry. i'm
down with left-aligned if you think it is the best compromise.

**Comment by envygeeks** [comment]
Please do also increase the maximum and implement simple flex widths:

```less
.settings-view {
  .section-container { max-width: 804px; }
  .config-menu { flex: 16%; max-width: 240px; }
  .panels { flex: 84%; }
}
```

**Comment by envygeeks** [comment]
On a side note, you could also min-width the `.config-menu` too, to keep the flex from under-sizing it if it goes below a certain depth but i found it acceptable till just before `1280`

**Comment by simurai** [comment]
@envygeeks That's a good suggestion. Should be in `174`. Thanks.

The `min-width` on `.config-menu` is added as well, so it doesn't get squeezed when using split panes.
