### ISSUE TITLE
Buttons don't wrap well

### ISSUE THREAD

**Issue by kevinsawicki** [atom/settings-view#342]
![screen shot 2015-01-13 at 12 21 33 pm](https://cloud.githubusercontent.com/assets/671378/5728450/27795280-9b1f-11e4-911c-075062bf1f2a.png)

**Comment by simurai** [comment]
The buttons are now shown separately and not in a group, since there is now way to tell when a button gets wrapped. We need "element queries" like yesterday!

![screen shot 2015-01-14 at 12 14 37 pm](https://cloud.githubusercontent.com/assets/378023/5733535/c423296c-9be7-11e4-9c8e-786b8bea1464.png)

![screen shot 2015-01-14 at 12 14 16 pm](https://cloud.githubusercontent.com/assets/378023/5733550/d50200e6-9be7-11e4-8aaf-b103e4931627.png)

**Comment by thedaniel** [comment]
:sparkles:
