### ISSUE TITLE
Package versus "core package" distinction confusing

### ISSUE THREAD

**Issue by benbalter** [atom/settings-view#35]
Atom should make it clearer what's a core package, or at least what core packages are installed to avoid confusion when searching for a core package returns no results.
## A story

So I open up my shiny new editor, head over to "packages" to customize it and directs me to https://atom.io/packages to see what's available. Awesome. `find-and-replace` is the most downloaded. That sounds like something I'd use. Let me search for `find`. No results. Confused. I eventually see something in the settings sidebar to indicate that the package is installed already, but it was a long path to get there mentally after seeing no results found..

**Comment by andrewleith** [comment]
I don't really consider this closed. 

There should be *ONE* tab that deals with packages in the "Settings" tabs. Results from searching both could be displayed.  In any event, as a new user it would seem more usable to me to search the available packages in the community by default rather than the ones their software is telling them they installed.  

In any event, for a new user (such as myself) this may make it seem like there are not many packages in the Atom eco-system.
