### ISSUE TITLE
  Settings->Packages page scroll position is not remembered

### ISSUE THREAD

**Issue by TheBestPessimist** [atom/settings-view#361]
First time user, fresh install, but long time Sublime text 2/3 user (more than 2 years).
After i installed atom, i went to settings to check all the options, and one thing that really annoyed me was that after i click a package name (or the settings button for that package), to see its configs/properties, if i click at the top of the window "Packages" again, the list position is reset, so for example if i am at the middle of the list, i have to scroll again and find my position.

Also another thing is that if i click (in the same menu) multiple times the "Settings' button, i can not see the "Packages" button at the top, so my only possibility is to go on the left panel and click "Packages" there (this again resets my scroll position)

**Comment by mnquintana** [comment]
Hmmm, that's an interesting idea. It hasn't bothered me that much that the list position resets when you reload the Packages pane, but I could see how that would be really annoying especially if you were just going down the list configuring settings for your packages, so I think :+1:. I think there should still be some way to reset the list position (or jump to top) if this enhancement is added though. Maybe you just click on "Packages" a second time? I'm not sure.

Your last suggestion was reported in #358

**Comment by TheBestPessimist** [comment]
I read #358, but i didn't know that was named "breadcrumb". Sorry for that duplicate.

**Comment by eboracus** [comment]
Yes, I was coming to suggest this. This would be extremely useful, currently wanting to just look at the readme info on a package means starting from the top of the list again. That makes looking for the right package you want to install a chore.

Maybe a standard browser-like 'back' button next to the breadcrumb at the top of the page, so that clicking on back returns to previous position and clicking on the breadcrumb (or the packages button on left) returns to the top?

**Comment by scherii** [comment]
@mnquintana
>Maybe you just click on "Packages" a second time? I'm not sure.
I think this is exactly the behavior someone would expect.

Another way of solving this: Just provide a way to open a package detail in a new tab (#462). Yes, I know that this is more of a workaround. And I still would like the package list to remember the scroll position :smile:

**Comment by jancborchardt** [comment]
Same here, has been bothering me since forever. There’s no obvious means of going »Back« from the package detail view, the closest to that is the »Packages« link in the breadcrumb above. If that’s used, the scroll position should not be reset but rather be where I was before.

**Comment by Redsandro** [comment]
Any progress on this? I'm new to Atom and this is the first annoyance. I was going to create an issue for this, but I see this one already exists.

My annoyance use-case:

* Carefully browse down to find something on the `Browse Settings` -> `Keybindings` page
* Copy a keymap
* Switch to a panel with `keymap.cson` for editing
* Switch back to Keybindings page to look for next item
* `Keybindings` page has scrolled back to the top :rage1:  :rage4:  :finnadie:

**Comment by ediamin** [comment]
Please fix this issue. It's really annoying.

**Comment by grady404** [comment]
Is this being actively worked on? It's extremely annoying, and it seems like it would take about two seconds to fix.

On a side note, there should also be a way to open a settings sub-menu in a new tab.

**Comment by lee-dohm** [comment]
@grady404 No, it isn't being actively worked on. Often you would see PRs or commits linked to this issue when something is being worked on.

> it seems like it would take about two seconds to fix.

I consider this insulting or derogatory, which is a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md). You may consider this an official warning.

On a more constructive note, because Atom is open source, anyone can contribute to the project. If you have a simple fix, I would be happy to review it for you :grinning:

**Comment by grady404** [comment]
Sorry if that came off as an insult, I really didn't mean it that way. I'll definitely look into some of Atom's source code to see what I can do. Thanks for the quick response :)

**Comment by Redsandro** [comment]
@grady404 as a workaround you can open a new instance of Atom with only the keymap open. It's not competitively pretty, but it's effective.

I probably shouldn't have said that, because I'd love to see a PR to fix this seemingly simple problem. I believe those pages are 'live' views that refresh when switched to. Theoretically clever but practically annoying. They should only refresh when a package is installed, removed, or (de)activated.
