### ISSUE TITLE
Uninstall button of deactivated packages is gone

### ISSUE THREAD

**Issue by olmokramer** [atom/settings-view#501]
Deactivated packages no longer show an uninstall button in the packages list as well as the package detail view. It's only packages that were deactivated at the time the settings view is opened.

**Comment by dantman** [comment]
This is a problem for me to. One of the packages I use has a bug in it that makes it impossible to use Atom. I went into safe mode to manually disable it by editing my config file. Now I can't uninstall it from the settings view (to see if re-installing and/or upgrading will fix the problem). And I can't re-enable it to uninstall, because doing that would break Atom in a way that would prevent me from getting to the settings panel.

**Comment by mnquintana** [comment]
@dantman In the meantime you can uninstall the offending package with `apm uninstall package-name`

**Comment by dantman** [comment]
Yeah, I looked at that right after posting. It worked, and re-installing that package did workaround the Atom breaking bug in that package.

**Comment by benogle** [comment]
Is this still an issue? I see uninstall buttons on disabled packages.

![screen shot 2015-07-01 at 4 56 03 pm](https://cloud.githubusercontent.com/assets/69169/8467354/148dcf7a-2012-11e5-9754-03b0c9c59f50.png)

**Comment by olmokramer** [comment]
It works again on my end. Thanks for fixing this! :heart:
