### ISSUE TITLE
Highlight keystroke collisions

### ISSUE THREAD

**Issue by zephraph** [atom/settings-view#510]
It would be useful to be able to glance at the keybindings view and tell right away what conflicting keystrokes I have. Maybe we can highlight redundant keybindings?

**Comment by lee-dohm** [comment]
Because the atom-keymap package uses CSS selectors to scope key bindings to certain areas of the application, it is very hard to statically determine the full set of *conflicting* key bindings. For example, do these two key bindings conflict?

```coffee
'body .native-key-bindings':
  'alt-left': 'native!'
'atom-text-editor':
  'alt-left': 'editor:move-to-beginning-of-word'
```

They both use the same key combination, but most would not consider that a conflict since the `atom-text-editor` version of the key mostly mimics the native key binding in a more specialized setting.

If you scroll through the list of key bindings in the Settings View, you'll notice that there are a *lot* of overlapping key bindings. But just because they overlap doesn't mean they conflict.

I think this could be a good idea if someone could come up with a heuristic for statically determining conflicts.
