### ISSUE TITLE
Packages linked to ~/.atom/packages don't display Readmes

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#550]
Steps to reproduce:

1. Clone a package.
1. `cd` into that directory.
1. `apm link`
1. Reload Atom
1. Open up the package detail view for that package in Settings View
1. Scroll to the Readme section
1. There will be the following error: `ERROR: No README data found!`

**Comment by mertzt89** [comment]
confirmed. I am experiencing the same issue.

**Comment by t9md** [comment]
I quickly checked issue,  its seem [this line](https://github.com/atom/settings-view/blob/master/lib/package-detail-view.coffee#L116) won't never null, since `@pack.metadata.readme`  set to 'ERROR: No README data found!!'.
So I need to investigate where `metadata.readme` is set.

**Comment by t9md** [comment]
From atom v0.199,  packages metadata become [normalized](https://github.com/atom/atom/commit/97ad2f30e028eb24320f86390aadb3a4b8bd09d2) with `normalize-package-data` and it set (ERROR: No README data found!)[https://github.com/npm/normalize-package-data/blob/2b006a6d53490fc053ba5ee727d36fbb4ff64868/lib/fixer.js#L227-L232] string.

By this change, pack.metadata.readme always set `string` data.
So [this line](https://github.com/atom/settings-view/blob/master/lib/package-detail-view.coffee#L116-L117) never be true, since readme is never be set `null`.


I can't judge where (atom side or settings.views specific logic) to be fixed.
Hope this investigation helps to get fixed.

**Comment by nemoDreamer** [comment]
:+1:

**Comment by rrd108** [comment]
I have the same issue with my own package.

**Comment by nemoDreamer** [comment]
:lollipop:'s for @mnquintana !!!
