### ISSUE TITLE
Atom 1.0 will consume 100% CPU when managing packages

### ISSUE THREAD

**Issue by mnquintana** [atom/settings-view#555]
_From @lovio on June 26, 2015 6:7_

No matter installing or uninstalling packages, `Atom Helper` will comsume over 100% CPU.

_Copied from original issue: atom/atom#7438_

**Comment by mnquintana** [comment]
_From @hax on June 26, 2015 7:53_

me 2. `atom --safe` doesn't help.

**Comment by mnquintana** [comment]
_From @jellymann on June 26, 2015 7:54_

I am using Atom 1.0 on OS X, and the Atom Helper process is using a maximum of 40% CPU during package updates.

What is your system information?

My system:
 * OS X 10.10.2
 * 2012 Retina MBP 
 * CPU: 2,7 GHz Intel Core i7

**Comment by mnquintana** [comment]
_From @hax on June 26, 2015 8:11_

Seems the problem of nuclide.

**Comment by mnquintana** [comment]
_From @bsbhro on June 26, 2015 10:21_

Other processes consume over 100% too. My terminal gave a hint: X-Window error (Ubuntu1504). Often the error message with "Keep Waiting", but the high memory consuming remains. I can't work with this version...

**Comment by mnquintana** [comment]
_From @samueloph on June 26, 2015 13:48_

This is happening to me too, since v0.211.0.

Running Debian Stretch here.

When I try to check for package's updates, some atom process starts eating all the memory.

**Comment by samueloph** [comment]
Is there some dev. following this issue? This is a very grave bug, I can't use Atom at all, I did check a guide on how to debug atom but nothing helped.

Tried to reinstall too, didn't solved.

**Comment by batjko** [comment]
Problems like this tend to be very high on the core devs' priorities. I'm sure it won't be long.

**Comment by samueloph** [comment]
Quick Update Guys, It looks like removing atom and all its config. files resolves the problem.
Could this bug result from some dirty update? It started happening one version before the 1.0.0 here.

**Comment by samueloph** [comment]
Ok, Quick Update, It looks like this bug is caused by Nuclide https://github.com/facebook/nuclide/issues/84#issuecomment-117889366

The strange thing is, it happens even with atom --safe

**Comment by batjko** [comment]
It's certainly not caused by Nuclide as there are enough documented cases of this and related issues where Nuclide was never installed.

But it could certainly be something that Nuclide is either exacerbating or is otherwise particularly vulnerable to.

**Comment by samueloph** [comment]
So, should this be closed since nobody replicated it?
Can we assume it's fixed?

**Comment by Stanzilla** [comment]
This issue is two parted, one was the Nuclide bug, the other are the general freezes and lags that happen when browsing or installing packages. You can follow this issue for the latter https://github.com/atom/atom/issues/7275

**Comment by LegNeato** [comment]
This sounds like my issue that I just linked. I can repro 100% with Nuclide installed (even in safe mode) and it happens on launch even if the settings UI is not shown.

I think that my problem is in `BufferedProcess`...it seems to be in a tight read or event loop. I can comment out https://github.com/atom/atom/blob/8b40c3aaeba4c98730b8d5451b6aba1f09b55911/src/buffered-process.coffee#L75 and the CPU use goes away after it was being repro'd 100%.

Interestingly, when I dump out the command Atom Helper is hung on:

`/Atom.app/Contents/Resources/app/apm/bin/apm ls --json --no-color`

And run it manually in a terminal it is fine.

my problem is definitely caused by the built-in settings view somehow. Master "works" because there is a coffeescript error, but when I load the latest release (atom/settings-view@cb09a2d) I get the high CPU use.

When I comment out https://github.com/atom/settings-view/blob/master/lib/package-manager.coffee#L43, everything (except the settings view) works, no 100% CPU usage.

**Comment by LegNeato** [comment]
@samueloph Can you try the PR directions in https://github.com/atom/atom/issues/3426 and let me know if it fixes it for you?

**Comment by thedaniel** [comment]
I merged #674, which should address this in the next release of settings-view (0.228.0). If it doesn't, please reopen and we'll investigate further. (cc @LegNeato)

**Comment by ElegantScripting** [comment]
I have this issue as well.
