### ISSUE TITLE
Provide a list of available fonts instead of asking the user to type the name

### ISSUE THREAD

**Issue by izuzak** [atom/settings-view#57]
It would be cool if the settings view provided a dropdown list of available fonts (or an autocomplete feature?) instead of asking users to type in the font's full name. 

![screen shot 2014-03-03 at 10 10 57 pm](https://f.cloud.github.com/assets/38924/2314550/5eea1e20-a318-11e3-9411-bd4f9dabb8bb.png)

**Comment by plttn** [comment]
Interestingly enough, trying to set M+ as the mono spaced font in Chrome beta40 also fails with the same fallback font as mentioned in #2919, so this may not be an issue that can be fixed on the atom end.

**Comment by X-Stranger** [comment]
For Terminus TTF the font family is 
```'Terminus (TTF)'```
with quotes. Spent half an hour... 'M+' is a piece of crap, it does not help to select Terminus, so it can be the fix for that issue.

**Comment by yuttie** [comment]
Finally, I successfully configured Atom so that it shows texts with multiple fonts.
Quote font names and separate them with comma, e.g. 'Envy Code R','M+ 1m'.
Thanks @X-Stranger !

**Comment by mnquintana** [comment]
Closing in favor of #286, which has more discussion about implementation.

**Comment by grandsong** [comment]
**I highly advocate auto-completion**, which suggests but **DOES NOT FORCE** a user to select from the font name list.

Otherwise, **a drop-down menu will hurt** me as well as many users whose natural language is not Western. In my case, Chinese.

---

I wrote a long issue to explain:

1) Why is Atom so different from other editors with regard to setting the font?
2) Why is "Font Family" is great for non-Latin users?
3) Why do I advocate auto-completion instead of drop-down menu?

If you are interested, please [read the whole issue](https://github.com/atom/settings-view/issues/525).
