### ISSUE TITLE
Settings button doesn't show up

### ISSUE THREAD

**Issue by izuzak** [atom/settings-view#573]
_From @bronson on July 7, 2015 6:17_

find-and-replace has settings so it seems strange that the Packages list doesn't show a Settings button for it...?

![bug3](https://cloud.githubusercontent.com/assets/1776/8539850/249df238-2435-11e5-9e5a-8034a344a538.gif)

_Copied from original issue: atom/find-and-replace#439_

**Comment by izuzak** [comment]
_From @thomasjo on July 7, 2015 7:1_

I'm unable to reproduce, but I'm running `HEAD`. Are you able to reproduce in safe mode?

**Comment by izuzak** [comment]
I'm running the latest version of master (1.0.1-ed735d8) and was able to reproduce this:

![sett](https://cloud.githubusercontent.com/assets/38924/8542076/2fbe6ce8-2493-11e5-8db9-a08472bdf161.gif)

Seems like some packages have a Settings button, and some do.

**Comment by izuzak** [comment]
_From @thomasjo on July 7, 2015 8:32_

This is really weird... it's missing here now as well. Heisenbug?

**Comment by izuzak** [comment]
cc @benogle who's been fixing lots of issues in Settings View recently :sparkles:

**Comment by benogle** [comment]
This seemed random because it depended on 2 things:

* Was the package activated? (find and replace is activated on an `activationCommand`)
* Was there anything in the config related to the package.

So when the package was not be activated, and nothing was set from your config file, the button would not show. The new implementation requires the mainModule from packages like find and replace, and checks for a schema.
