### ISSUE TITLE
Images broken on available updates

### ISSUE THREAD

**Issue by clemmy** [atom/settings-view#595]
<img width="1440" alt="screen shot 2015-07-19 at 2 53 34 pm" src="https://cloud.githubusercontent.com/assets/3696934/8767416/281b5ce4-2e2a-11e5-8fce-47c96790fd2d.png">

**Comment by mnquintana** [comment]
I've reproduced this with Atom 1.0.3-0fe4183, but not consistently. I think this can happen in any view with package cards though - not just the Updates panel.

/cc @benogle

**Comment by rjv** [comment]
Seeing same issue on Windows 7, Atom v1.0.3.

**Comment by jensljungblad** [comment]
+1

**Comment by vjandrea** [comment]
+1

**Comment by joshschumacher** [comment]
I've been annoyed by this small bug for a long time too, decided to try to look into it. Opened up the inspector view (View > Developer > Toggle Developer Tools) to inspect one of the failing avatars. Weird thing was, inspector thought the image was just fine - it showed a popup preview when I hovered over the image src (file:///Users/josh/Library/Application%20Support/Atom/Cache/settings-view/tststs-1445582599869). Went to view that image directly on the filesystem and it was hunky-dory. Reloaded the Updates panel to watch a network inspector load and what do you know - all of the images loaded.

Hoping maybe the repro steps will help someone that is familiar with the code base because now it's working for me and I can't reproduce  ¯\_(ツ)_/¯

**Comment by defeated** [comment]
Confirmed this is still happening in Atom 1.5.3 -

![](http://cl.ly/2M1d2z2M2A0Z/Image%202016-02-14%20at%2011.00.22%20AM.png)

**Comment by davidspiess** [comment]
I think the problem is a wrong mime type. I can see two image request in my dev tools. The first call with type `text/plain` which obviously is broken.

![image](https://cloud.githubusercontent.com/assets/992674/13696974/7d03f898-e76a-11e5-9023-d29a62256404.png)

**Comment by senoadiw** [comment]
Deleting the settings-view dir in %userprofile%\AppData\Roaming\Atom\Cache and reloading the window seems to regenerate the icon cache.

**Comment by deakster** [comment]
Deleting the folder @senoadiw mentioned did fix it for me briefly, but the issue came back pretty quickly.

**Comment by berniedurfee** [comment]
+1

Atom 1.6.2
Mac OS X - 10.10.5 - Yosemite

**Comment by nicholasdunbar** [comment]
I am having this problem as well. 

+1

Atom 1.6.2
Mac OS X - 10.11.4 - El Capitan

**Comment by dbwest** [comment]
+1

**Comment by zacharyjsnow** [comment]
+1

**Comment by digeomel** [comment]
+1 on atom 1.7.4 behind proxy

**Comment by yustnip** [comment]
The same. Also through proxy.

**Comment by brentaquent** [comment]
+1 atom 1.7.4 Ubuntu 16.04 but no proxy.

**Comment by danielmahon** [comment]
+1 Atom 1.8 OSX El Capitan

**Comment by MichaelAquilina** [comment]
+1 Ubuntu Atom 1.7.4 no proxy

**Comment by rdmcgregor** [comment]
+1 Atom 1.8 OSX El Capitan

**Comment by jmdelros** [comment]
+1 Atom 1.9 behind a proxy

**Comment by MichaelAquilina** [comment]
Random note while I was looking into this. I tried inspecting using the developer tools and I set the width of the `img` element to 20 and it seemed to fix itself. Dont know if this is just a side effect of the browser reloading the image after it becomes available though.

**Comment by bastilian** [comment]
I think I found what the issue is.

When the images are requested, it might happen that they time out, but a file still gets saved, which is not an image and therefore causes broken avatar images.

#813 will include a fix that removes the file in case of an error and hopefully will address the issue.

**Comment by 50Wliu** [comment]
@bastilian I think that's a different issue (#327).  The issue here is that _all_ avatars are showing as broken on the Available Updates page while they work fine on others, such as the Install pane.

**Comment by cvega** [comment]
+1 Atom 1.9.6, OSX - El Capitan (10.11.6)

**Comment by damieng** [comment]
I'm not convinced this is a different issue - it also goes direct to the cache and attempts to load files just like the other pages and they both display the broken indicator if that file is corrupt/zero bytes.

**Comment by damieng** [comment]
Rewritten a bunch of the avatar image caching code to better handle bad responses, errors and non-image bodies and not cache them. This should solve these issues and the ones in #327 better than the size check (it would previously cache 500 errors as an image) and is better performing.
