### ISSUE TITLE
Disabling packages should also disable sub-packages

### ISSUE THREAD

**Issue by Stanzilla** [atom/settings-view#606]
Example: Disabling linter should disable all packages that depend on linter being enabled.

**Comment by olmokramer** [comment]
There is currently no way to tell if a package depends on another package. Yes, packages can consume services from another package, but that isn't always a *dependency* because some packages work just fine without that service being provided.

For example, my [autohide-tree-view](https://atom.io/packages/autohide-tree-view) package consumes the service provided by [atom-touch-events](https://atom.io/packages/atom-touch-events) to allow users to open and close the tree view with swipe events, but there's a ton of other features in autohide-tree-view that don't depend on the touch events, so autohide-tree-view shouldn't be disabled when atom-touch-events is disabled.

**Comment by 50Wliu** [comment]
Closing because Atom does not recognize any package dependencies.
