### ISSUE TITLE
Hide collapse icon when there are no items shown

### ISSUE THREAD

**Issue by simurai** [atom/settings-view#636]
On Twitter: 
![screen shot 2015-08-18 at 9 50 55 am](https://cloud.githubusercontent.com/assets/378023/9319949/2980da56-458f-11e5-87f2-458904b4e2b2.png)

Was also thinking the whole title could be hidden, but it's probably still useful to know that a section exists even when showing `0/0`. Especially when doing a search. Maybe "Deprecated Packages" could be hidden since it's more a temporary section.

**Comment by thomasjo** [comment]
I think we should take this one step further; if a section is empty, it shouldn't be interactive in any way. That means no "clickable" styling (cursor, etc.), and no click event handler. I guess for the time being it'd be sufficient to prevent the styling if it turns out that it's tricky to prevent the event wire-up.

**Comment by jeroldhaas** [comment]
Original tweet-person, here. Most accordion-style interfaces like that show as collapsed by default, no icon to expand-contract, and no icon change to falesely indicate to the user of its interactivity, so I think the combination of your solutions (whilst still showing the section to indicate its existence) is a best-fit.

**Comment by evjan** [comment]
The same should be true for the Themes section I suppose

**Comment by evjan** [comment]
I've got an idea for how to fix this, working on it now
