### ISSUE TITLE
Deep linking to a package's settings page 

### ISSUE THREAD

**Issue by francoislaberge** [atom/settings-view#702]
I'd like to have a button that opens up our package's settings. I was recommended this approach:
```coffee
atom.workspace.open 'atom://config/packages/<package-name>'
```

That works except when the settings page is already open, if it is, then it just stays at where it happens to already be navigation wise, rather than landing on the package's settings page. I haven't been able to find any work arounds yet for this. Any suggestions, solutions?

**Note**: I originally filed this to the atom repo: https://github.com/atom/atom/issues/9722

Thanks in advance,
Francois

**Comment by thedaniel** [comment]
Sounds like this behavior needs to be fixed in settings-view, I doubt there's an available workaround without changes in this repo.

If you'd like to dig into it yourself, this is where the uri is matched to a regex and showPanel is triggered: https://github.com/atom/settings-view/blob/master/lib/main.coffee#L22-L27

And here's showPanel: https://github.com/atom/settings-view/blob/master/lib/settings-view.coffee#L175-L186

**Comment by francoislaberge** [comment]
hmmmm. I no longer am seeing this issue at all. Looks like it was likely fixed in this commit: https://github.com/atom/settings-view/commit/12925c403ba3d11e13cc91ab1193bb2cb8f00e2c

**Comment by francoislaberge** [comment]
thanks @thedaniel !

**Comment by francoislaberge** [comment]
Hmmmm. It may not have been that commit. The issue seems to be gone though if it helps. Should I reopen till someone else confirms, or leave it closed?

**Comment by thedaniel** [comment]
If you're not seeing it anymore, just leave it closed - we can open again if someone else comments.

**Comment by francoislaberge** [comment]
Cool.
