### ISSUE TITLE
Uninstalling & reinstalling a package, then clicking on any Details links results in multiple files/windows opening

### ISSUE THREAD

**Issue by amytruong** [atom/settings-view#711]
**Steps to reproduce:**
1. Navigate to Settings View
2. Select a package
3. Install it
4. Uninstall and reinstall
5. Click on any of the detail links: "View on Atom.io", "Report Issue," Changelog."  or "View License" and you'll get 2+ windows displaying in Chrome or in Atom 

Note: Happens in Themes too

![chrome](https://cloud.githubusercontent.com/assets/10725993/11665572/f7d4975c-9d9c-11e5-83b3-0d79a1eb9c81.gif)
Mac OSX
Atom Version: 1.4.0 dev82c27e8

Maintainers: This might be a duplicate/already known issue, if so, please feel free to close and list the issue number for me so I can log it in my test manifest. Thank you!

**Comment by mgarciaisaia** [comment]
The action is being triggered multiple times because the [`handleButtonEvents`](https://github.com/atom/settings-view/blob/e86dc608711c142161baf0a404e5d6c8d6d0fec7/lib/package-detail-view.coffee#L194) function is being called through [`completeInitialization`](https://github.com/atom/settings-view/blob/e86dc608711c142161baf0a404e5d6c8d6d0fec7/lib/package-detail-view.coffee#L72) (called by [`loadPackage`](https://github.com/atom/settings-view/blob/e86dc608711c142161baf0a404e5d6c8d6d0fec7/lib/package-detail-view.coffee#L86)) each time [the `theme-installed` or `package-installed` event is emitted](https://github.com/atom/settings-view/blob/e86dc608711c142161baf0a404e5d6c8d6d0fec7/lib/package-detail-view.coffee#L178-L181).

So it gets re-registered upon any new installation, and the `shell.openExternal` gets called multiple times.

To fix this, we could try to empty the handlers of each button during the `handleButtonEvents` function, but it seems a bit hacky. The _real_ way of fixing this would be to avoid calling `handleButtonEvents` at all when not necessary, but I'm a bit too sleepy to understand how to do that.

I thought adding an `event.stopPropagation()` to the functions would be a quick&dirty workaround, but it wasn't - the callback would get multi-triggered anyway.

**Comment by m4jing** [comment]
Atom version: `v1.3.2`
OS: Mac OSX `10.10.3`
The same issue exists.
