### ISSUE TITLE
Color picker returns invalid HEX string.

### ISSUE THREAD

**Issue by silvestreh** [atom/settings-view#712]
When using the color picker in a package's settings, the `.toHexString()` method sometimes returns invalid HEX values for dark colors (close to black).

I resorted to catching those invalid colors using `tinycolor`'s `isValid()` method…

```javascript
atom.config.onDidChange('atom-material-ui.colors.accentColor', (value) => {
    var accentColor = tinycolor(value.newValue.toHexString());

    if (!accentColor.isValid()) {
        return atom.notifications.addError(`The selected color <code>${value.newValue.toHexString()}</code> is not a valid HEX value. Try another!`, { dismissable: true });
    }
    amu.writeConfig()
});
```

Just to be clear, I'm not talking about the [color-picker](https://atom.io/packages/color-picker) package. I'm talking about the color picker Atom gives us developers for our package's settings:

```javascript
"baseColor": {
    "title": "Primary color",
    "description": "Changes the main theme color.",
    "type": "color", // <-- This one!
    "default": "#009688"
},
```

Looks like this on OS X:

![captura de pantalla 2015-12-13 a las 2 58 24](https://cloud.githubusercontent.com/assets/1133339/11765770/797a4238-a145-11e5-8ffc-f3f455048907.png)

When changed, the `value.newValue` property is a `Color` object:

![captura de pantalla 2015-12-13 a las 3 04 38](https://cloud.githubusercontent.com/assets/1133339/11765793/7ef4c02a-a146-11e5-96a3-7e04be8435d2.png)

And its `toHexString()` method *sometimes* produces invalid HEX color strings. It happens with dark colors mostly.

**Comment by D-side** [comment]
Hello, I'm one of those who followed the link in your notification. It happens on Windows 10 as well, so it's probably not an OS-specific quirk.

The issue is with zeros. Currently, given 3 numeric color components, it seems to do the following for each:

* 0..9 => 00..09 (OK)
* 10..15 => A..F **(single digit without a leading zero!)**
* 16..255 => 10..FF (OK)

So now we've got a **specific definition** of "random, mostly dark colors". It's any color that has a value of `A` to `F` in one or two of the RGB components, such as:
  * (10, 255, 255)
  * (10, 10, 255)

These result in colors consisting of 4-5 hexadecimal characters. And there's no way to find what it was originally, it's ambiguous. Given `FADED` it could be `F` `AD` `ED`, or it might as well be `FA` `D` `ED`.

**Comment by lee-dohm** [comment]
Thanks @D-side for tracking that down!

**Comment by lee-dohm** [comment]
This should be out in v1.7.x.

**Comment by silvestreh** [comment]
:+1:
