### ISSUE TITLE
Settings view throws an exception if opened in a different pane from where it is already open

### ISSUE THREAD

**Issue by WalterGR** [atom/settings-view#723]
**Steps to Reproduce:**
1. Open Atom in safe mode
1. Ensure the `settings-view` is not open
1. Split right so you have two panes open
1. In the left pane open the `settings-view` using <kbd>Ctrl-,</kbd>
1. In the right pane open the `settings-view` using <kbd>Ctrl-,</kbd>
1. **Expected:** `settings-view` to focus on the already opened `settings-view` in the left pane, **Actual:** Exception in console
![image](https://cloud.githubusercontent.com/assets/1058982/21544558/4d85e458-cdd0-11e6-86cd-219371f6fe81.png)

From this state you can get weird errors like: https://github.com/atom/atom/issues/12498

Refs (Same bug in atom/about): https://github.com/atom/about/issues/30

----

Expected:

"n update(s)" and the icon disappear.  One of the Settings tabs is switched to and the "Updates" section displayed.

Actual:

"n update(s)" and the icon disappear.  Nothing else (at least visibly) happens.

Atom 1.4.0 in OS X 10.10.5.

Screen recording showing the bug:

![atom-clicking-update-available-in-status-bar-does-nothing-if-settings-are-open-in-multiple-tabs](https://cloud.githubusercontent.com/assets/380880/12376594/a58f9648-bcb1-11e5-81bf-0b1dcf5871d2.gif)

**Comment by WalterGR** [comment]
Here's another instance of incorrect behavior, which I think is probably due to the same bug.

Repro:

1.  Have Settings open in a pane.
2.  Make any tab other than that Settings tab be the active tab in that pane. (Or stated differently: ensure that the Settings tab isn't active.)
3.  Move focus to a different pane.
4.  Click the "n update(s)" text.

Expected:

"n update(s)" and the icon disappear. One of the Settings tabs is switched to and the "Updates" section displayed.

Actual:

"n update(s)" and the icon disappear. Nothing else visibly happens.  But Atom has opened Settings: in the active pane, _behind_ the current tab.

Screen recording showing this behavior:

![atom-clicking-n-updates-can-open-settings-behind-an-existing-tab](https://cloud.githubusercontent.com/assets/380880/12406950/f10a1ea8-be06-11e5-83d9-947e82f1ce29.gif)

Unfortunately the MOV-to-GIF converter I use speeds things up like an old silent film, but this is what you're looking at:

*  Cursor wiggles under Settings tab that isn't active.
*  A different pane is clicked to move focus there.
*  Click "2 updates".
*  Nothing appears to happen.
*  Turn on Key Binding Resolver.
*  Show that Settings has opened 'behind' the "Clojure REPL" tab by using `pane:show-next-item` and `pane:show-previous-item`.

**Comment by WalterGR** [comment]
(Updated title to account for my "Here's another instance of incorrect behavior" comment above.)

**Comment by Ben3eeE** [comment]
I'm pretty sure this issue describes the same thing as https://github.com/atom/atom/issues/11199, just that this has a different way of opening the settings view.

**Comment by 50Wliu** [comment]
Here's the current behavior.  Exception still shows up in console.  Pretty odd.
![multiple-settings-views](https://user-images.githubusercontent.com/2766036/34508568-05d32f00-f00f-11e7-9ecf-0b1fbdc548f5.gif)

**Comment by t9md** [comment]
I was investigating this.
Now I'm clear why this happens.

Trying to send PR after think a bit more.

To make explanation clear, I will
- Refer `setting-view` as SV
- Use open's URI(`atom://config`) directly instead of saying "invoke `settings-view:open`
  - `settings-view:open` invoke `atom.workspace.open("atom://config")`
  - `settings-view:core` invoke `atom.workspace.open("atom://config/core")`
  - `settings-view:change-themes` invoke `atom.workspace.open("atom://config/themes")`

# Preparation

open two panes(`p1` and `p2`), then activate `p1`, open `atom//config`

```
            p1(active)                 p2
+-------------------------+-------------------------+
| atom://config           |                         |
|                         |                         |
|                         |                         |
|                         |                         |
|                         |                         |
+-------------------------+-------------------------+
```

- When p1 is active
  - OK: `atom://config`
  - OK: `atom://config/core`
  - OK: `atom://config/themes`

- When p2 is active
  - NG: `atom://config` by trying to open cached `settingsView` item on pane `p2`
  - OK: `atom://config/core`: p1 activated
  - OK: `atom://config/themes`: p1 activated

# Why?

Short explanation
  - When trying to open specific panel, it make already opened setting-view's pane active **in opener**.
  - So calling `pane.activateItem(item)` have no issue.
  - But when trying to open without panel(just `atom://config`), it have no panel path. SV's pane is not activated in opener.
  - So calling `pane.activateItem(item)` is called against different pane of already opened SV's pane which result
  - Which is trying to open exact item in different pane `The workspace can only contain one instance of item`

### How it happens

Later two URI's(`/core`, `/themes`) have panel's path and it invokes `settingsView.showPanel(panelName, options)`

https://github.com/atom/settings-view/blob/b2b12887176e4a4e81f83d9b20dd448bd617ec9d/lib/main.js#L30

Which eventually call `panel.focus`, which make already opened `setting-view` item's pane active.
https://github.com/atom/settings-view/blob/b2b12887176e4a4e81f83d9b20dd448bd617ec9d/lib/settings-view.js#L312

Then this line's `container.getActivePane()` return's same pane of already opened `setting-view` item.
https://github.com/atom/atom/blob/8ba04f0f0c184ab1522be5129ad511752d2c3e9c/src/workspace.js#L1001


### Quick solution

- Activate setting's view item **in opener** regardless of URI have panel path.
- Which eventually simulate `searchAllPanes: true` option in `workspace.open`.
- No longer trying to open SV's item in different pane.
- Why we can't use this option here is SV item's `getURI()` is not usable as identity of item(URI is set to URI which initially created).
