### ISSUE TITLE
Slow loading of packages tab due to BufferedProcess

### ISSUE THREAD

**Issue by chuckhendo** [atom/settings-view#734]
The loading of the Packages tab is really slow. I did some research just now to set what might be causing this, and it seems to have something to do with the BufferedProcess module in core. If I make a spawn manually in package-manager.coffee, my load times (excluding rendering) are reduced from ~8s to ~1.5s. I achieve the same results if I comment out the following lines in BufferedProcess:

```coffee
      lastNewlineIndex = buffered.lastIndexOf('\n')

      if lastNewlineIndex isnt -1
        onLines(buffered.substring(0, lastNewlineIndex + 1))
        buffered = buffered.substring(lastNewlineIndex + 1)
```

I'm honestly not sure what the purpose of those lines are, but the lastIndexOf in particular is really slowing things down. Is there any particular reason BufferedProcess is needed rather than making a call to spawn directly? Or even better, is there not a way to tap into apm directly without having to make a shell call?

**Comment by lee-dohm** [comment]
I know that part of the reason for `BufferedProcess` is to standardize the interface of dealing with external processes across platforms. As far as tapping into apm directly, that is not currently possible because Atom and apm use different versions of Node.

Thanks for your interest! If you want to do more research and submit a PR including findings for test results (both performance and functional), we would definitely be interested in seeing your results!

**Comment by chuckhendo** [comment]
@lee-dohm Do you know if there any plans to eventually make direct access to apm possible? I have no problem looking into this, but wouldn't want to waste my time if direct apm access will be possible.

**Comment by lee-dohm** [comment]
I don't know of any plans, no.
