### ISSUE TITLE
Show keybindings of a package with namespace different from package name

### ISSUE THREAD

**Issue by hasit** [atom/settings-view#772]
Hello,

I came across this while using [navigator-godef](https://github.com/joefitzgerald/navigator-godef) package. The issue here is that, while keybindings are provided by the author, Atom settings-view page does not recognize them.

I have started a thread [here](https://discuss.atom.io/t/keybindings-wont-show-in-settings/28024) to discuss the issue and learnt that Atom only picks up the keybindings if the namespace is the same as the package name. The namespace (in this case, 'golang') is different from its package name (in this case, 'validator-godef).

Further, I talked to the author of 'navigator-godef' @joefitzgerald [here](https://github.com/joefitzgerald/navigator-godef/pull/5), and he said that this is by design since he wants to have the same namespace for his suite of golang packages for Atom. This makes sense because one can easily lookup all available packages by typing 'golang' in Command Pallet.

My question is, is there a way to show the keybindings present in the package regardless of the namespace used?

**Comment by lee-dohm** [comment]
Many parts of Atom assume that the namespace of a package is the same as, or trivially derived from, the package name. Keybindings is only one of these pieces. @joefitzgerald has brought this up to me directly and I will talk with him about potential solutions. When we come up with something, we will document it on the atom/atom repo since the impact could be rather far-reaching.

**Comment by hasit** [comment]
Perfect! Thank you so much for all your help. This would be a big change and I am looking forward to updates on this.
