### ISSUE TITLE
Merge "Install" section with "Packages" section

### ISSUE THREAD

**Issue by adamreisnz** [atom/settings-view#825]
I can't count anymore how many times I've wanted to install a new package, went to settings, clicked "Packages" and started to type the package name in the search box waiting and staring at the screen while nothing happened...

The two interfaces "Packages" and "Install" are so similar that it's really hard to keep the two apart. Why don't we merge them into one, called "Packages" to avoid confusion?

To me it seems intuitive that if you want to install "packages" you go and click on "packages" first, especially since that's the first item that you see when you're scanning the menu options from top to bottom.

Even adding a "install new packages" button in the "packages" section linking to the "install" section would help tremendously I think.

(Ref: https://github.com/atom/atom/issues/12316)

**Comment by simurai** [comment]
Yeah, not the first time I hear about this. :grimacing: Something to think about:

- Would the "Featured Packages" also be moved to "Packages"? Or maybe they would just show up if you filter/search? Or we remove them altogether?
- Would there be a difference between filtering and searching? Maybe just typing = filtering installed packages, hitting `enter` =  search for non installed packages. But that might be hard to discover. Would need a search button or the placeholder text could read something like: `Filter packages by name, hit enter to search for new packages`.
- After hitting `enter`, would only the search results be shown or also the already installed packages if the name matches? If the later, might not be easy to prioritize. What should be shown first.

Hey, another thought. How about moving the "Update" and "Install" to an entirely different package and therefore different pane. Not sure how to call it, but it would be similar to an "app store" where you discover, install and update packages, basically everything **new**. And for everything **existing** you would open the Settings View.

**Comment by adambuczynski** [comment]
> Would the "Featured Packages" also be moved to "Packages"? Or maybe they would just show up if you filter/search? Or we remove them altogether?

I would vote for removing them. I don't think this is a feature that is required to be visible in the editor. It would be more fitting to have it listed somewhere on the Atom website in my opinion. 

Personally, I just install packages that I need, and I don't think I ever installed a package that was featured just because it was featured. But that might not mean much, as I behave like that in for example the Android app store as well. I just use it to get/find the apps I need, and don't care to try/install apps that other people mark as featured for whatever reason. 

> Would there be a difference between filtering and searching?

What you suggested might be workable. The placeholder sounds like a reasonable option.

Alternatives would be a small checkbox/toggle to the right of the input field, to toggle between filtering installed packages and searching for online packages, or the added search button like you suggested.

> After hitting enter, would only the search results be shown or also the already installed packages if the name matches? If the later, might not be easy to prioritize. What should be shown first.

I would say show both. If the name matches, and the package is installed, it's good to know that the package is installed. It would be odd if you did a search for `linter-eslint` and didn't find it in the search because it was already installed.

As for prioritization, just apply the current rules, or simply alphabetically. I don't think you need to show installed packages with priority over online search results, as long as they both appear in the list.

When you're just filtering though, it should only show the installed packages. Maybe when nothing is found when you filter, it could show a message with a hint like "No matching installed packages. Try searching online instead."

> Hey, another thought. How about moving the "Update" and "Install" to an entirely different package and therefore different pane. Not sure how to call it, but it would be similar to an "app store" where you discover, install and update packages, basically everything new. And for everything existing you would open the Settings View.

Interesting idea, but that might confuse people just the same, as there would still be 2 places to manage packages. In the app store (Android at least), if you go to it and open a package that you have installed, it will show up and it will show you that you have already installed it, with an option to open it.

Since Atom already does that as well (it shows installed packages in the `install` pane), I feel like it'd be easier to merge the two. Because right now, you can essentially manage your installed packages from the `install` pane as well as from the `packages` pane. So it seems the `packages` pane is redundant, apart from the filtering function.

As for updates, I think my preference would be to just have those be done automatically behind the screen (or perhaps use a configuration setting to have auto updates turned on). I just want to have the latest stable version of packages, so I always want to update them, and having to do it manually is just another time waster for me.

**Comment by simurai** [comment]
> Maybe when nothing is found when you filter, it could show a message with a hint like "No matching installed packages. Try searching online instead."

That's a great idea. ❤️

> I would vote for removing them (Featured Packages).
> Interesting idea (app store package), but that might confuse people just the same, as there would still be 2 places to manage packages.

Yeah, I would also be ok letting only atom.io focus on package discovery. Even more so, if it's possible to open/install packages from atom.io directly. [Here an initial effort](https://github.com/atom/atom/pull/11399). Currently it's a bit cumbersome with having to copy&paste the package name.

**Comment by rugk** [comment]
> I would vote for removing them.

No, I really like them. And I certainly don't want to go the website each time I wan t to see the "top" packages.

As for the issue itself: When they are really combined it should be possible to search for new packages while the installed list is still loading and vice versa. Otherwise you would have the delay you get when accessing the "packages" tab when you have many packages installed also when you just want to install a new package.

**Comment by adambuczynski** [comment]
Then how about a separate section for those, `Featured packages`?
Not everyone is interested in seeing random featured packages every time they want to manage their installed packages.

**Comment by simurai** [comment]
> @adambuczynski Then how about a separate section for those, Featured packages?

Seems like a good compromise. So basically:

1. Rename `Install` to `Featured`
2. In `Featured`, **remove** the search functionality
3. For `Packages/Themes` **add** search functionality (type to filter, enter to search)

**Comment by adambuczynski** [comment]
Sounds good to me. And ensure for `3.` that when searching, it will also display installed packages if the name matches.

What are we doing with `updates`? Merge that into the packages pane as well or keep separate?
If it's kept separately, it would be nice to also show the update button next to an existing package if you're filtering/searching.

**Comment by simurai** [comment]
> And ensure for 3. that when searching, it will also display installed packages if the name matches.

Yeah, and just a flat list (without the categories). Basically the same as the current search under `Install`. I guess there needs to be a close [x] or so. To go back to show all the categories. `esc` shortcut would also be handy.

> What are we doing with updates? Merge that into the packages pane as well or keep separate?
If it's kept separately, it would be nice to also show the update button next to an existing package if you're filtering/searching.

I think it should still be separately listed. For easy access to the `Update All` button. But yes, I agree on having the update button everywhere (on all package cards). 👍

**Comment by rugk** [comment]
>For easy access to the Update All button. 

I think it should be possible to also integrate this button in the combined view. Maybe just list the updates on top of all "other" installed extensions.

**Comment by adamreisnz** [comment]
@simurai any progress on this issue?

I just found this which reminder me of this ticket:

![image](https://cloud.githubusercontent.com/assets/490562/21540236/cfd12584-ce12-11e6-827b-725a0ad62b6f.png)

Slack also has one search box with which you can find existing packages, but also new ones.

**Comment by simurai** [comment]
@adamreisnz Implementation hasn't started but we are thinking to overhaul the settings and will keep this issue in mind.

**Comment by adamreisnz** [comment]
Hey @simurai, any update on this issue? It's been more than a year ago since I raised this and unfortunately the UX for packages is still the same :(

**Comment by simurai** [comment]
> It's been more than a year ago since I raised this

🙈  Sorry, still no news. There was a plan to redo the settings but then priorities shifted.

An idea might be to create a separate package to manage packages. Maybe as a side panel/dock. You could only search, install, uninstall and disable packages. Clicking on one to change the settings would open the built-in settings-view.

**Comment by szeck87** [comment]
Yea I've never really understood why these were separated.  What about having a "switcher" button to go between installed and not installed (obviously rename the latter, I can't think of a good one right now)?  So something like:

1. Remove `Install`
2. Rename header in `Packages` to just Packages (instead of Installed Packages)
3. Placeholder text would just be Search packages
4. Put a switcher button set (like the current Packages/Themes on the `Install` page) to toggle between installed and not installed.  Installed search would just search installed packages. The not installed would have featured while the search finds packages the same as it does in the Install page today.

The only loss would be the toggle for Themes when searching.

@simurai is there an issue or old PR for the original plan to redo settings?

**Comment by saizai** [comment]
A few further suggestions for package install / search:
1. https://github.com/atom/atom/issues/12718 - don't list featured in a search context (but do list it before search is started, eg as a default suggested)
2. https://github.com/atom/settings-view/issues/297 - hide installed from featured list
3. add thumbs up/down ratings within Atom's interface
4. add `sort by`, `sort by (reverse)`:
 * relevance (current default)
 * alphabetic
 * # installs
 * rating (with some means of accounting for variance due to sample size and changes in more recent ratings)
   * this may deprecate the "featured" packages
5. add `filter by`:
 * package type (currently there's `packages` vs `themes`, but surely a better ontology is feasible)
 * tags (possibly user-submitted, e.g. to collect everything to do with a given programming language)
 * rating ≥ X
 * # installs ≥ X
6. For "installing X failed", add `try again` button next to `show output`, eg if it's a prereq that's been fixed or a network outage.
7. For packages with external dependencies, e.g. some npm package(s), add a popup requesting to install the dependency (and able to do so), rather than just failing and maybe showing a "please do this yourself" popup.

**Comment by szeck87** [comment]
I started some POC's based on my last comment.  Basically...

* Remove `Install` from the panel
* Put a button set in Packages to toggle between `Installed` and `Discover`
* Installed would show and function like the current Packages view as-is
* Discover would display featured packages by default, and the search would look for other published packages, just like Install does today.

The same thing would happen in Themes.

If this is something worth pursuing, let me know and I'll continue working on it.

![screen shot 2018-04-18 at 10 45 35 pm](https://user-images.githubusercontent.com/8315038/38970315-580d94e2-435a-11e8-988a-73d272be5ac8.png)
![screen shot 2018-04-18 at 10 45 57 pm](https://user-images.githubusercontent.com/8315038/38970316-581c2f5c-435a-11e8-94cb-9d5520d83e12.png)

**Comment by szeck87** [comment]
If anyone wants to take a look so far, see https://github.com/szeck87/settings-view/tree/install-merge.  There are quite a few things in `install-panel.js` that I'm not sure what it does, so I didn't move everything over to `installed-packages-panel.js` yet.

**Comment by lee-dohm** [comment]
This isn't something that we want to take on right now. We agree that the current situation isn't ideal but we would need to invest a bunch of design into the settings view that we don't have the resources right now to pick the right solution.

Thanks everyone for the feedback!

**Comment by adamreisnz** [comment]
That's really a pity to close this off after someone even proposed to help work on it. One and a half year of contributions and idea's have been poured into this, and it's really a severe UX issue with Atom's package management. After using Atom for years, it still bites me every time.

**Comment by szeck87** [comment]
@lee-dohm who is "we" exactly?  For an issue that has been open for a year and a half it seems pretty abrupt to close it just like that.

**Comment by lee-dohm** [comment]
"We" is the Atom maintainer team. I apologize for the closure of it being abrupt but it was left open as something that the Atom maintainer team was considering working on at one point. Obviously, it never got to the point where it was high enough priority for the team to invest the effort. We're trying to clean up old issues that we don't think will be addressed by the maintainer team in a reasonable time horizon. We're still figuring out what "reasonable" is but we're pretty sure coming up on two years is past that line.

**Comment by simurai** [comment]
Comment by @billygriffin 

> to me that is one of the most gigantic hurdles for beginners. i think that issue misses the core point and therefore the reason why it should be thought of as very high priority. when people want to install a new package and they're not really seasoned atom users, they go to "Packages" and they type in the one that someone told them about or that they read about, and when it doesn't show up, they assume it's no longer available or something is wrong, and then give up. that is basically the worst possible outcome for a product whose core value proposition is extensibility
