### ISSUE TITLE
Add "Tab Type" to language-specific settings list

### ISSUE THREAD

**Issue by lee-dohm** [atom/settings-view#835]
A couple language packages, specifically [language-python](https://github.com/atom/language-python) and [language-yaml](https://github.com/atom/language-yaml), override the `editor.tabType` setting. But this isn't shown in the language-specific settings list and therefore can't be discovered or customized easily.

**Comment by pdf** [comment]
I'd suggest perhaps both `tabType` and `softTabs` settings should be provided in language-* GUI settings, per discussion in #4054.

**Comment by lee-dohm** [comment]
We shouldn't need a `softTabs` language-specific setting if we have a `tabType` language-specific setting. `softTabs` is only necessary if the `tabType` setting is `auto`. So if you need a specific tab type for a given language, just set the `tabType` setting.

**Comment by pdf** [comment]
What's the harm in adding both?  What if the user wants to retain the `tabType` `auto` setting, but set their default preference for `softTabs` per-language?

More poignantly, some of the languages are setting `softTabs` (see [python](https://github.com/atom/language-python/blob/master/settings/language-python.cson)), so there ought to be a way to override that from the GUI.  Just adding both settings is the safe option, rather than making assumptions that may come back to bite users later.

**Comment by lee-dohm** [comment]
The harm in adding both is extra maintenance and confusion. If we could get rid of the `softTabs` option completely without breaking things, we would.
