### ISSUE TITLE
Font Family does not accept semicolons

### ISSUE THREAD

**Issue by DavidLGoldberg** [atom/settings-view#877]
On Atom *Beta*:
Reproduce with:
Editor Settings -> Font Family:
enter in a semicolon for example:
`Hack, monospace;`

Relates somewhat to #768 .

This caused me a bunch of issues in starting up.  Everything broken, no access to anything other than inspector.  When I had the hunch about the font family, I had to use Atom stable in order to play with the font family, to reset it back.

(Note:  Maybe Atom's safe mode (atom --safe) should consider resetting Font Family (and other settings, as it seems to not).

Once working I went back into atom-beta and was able to trigger the error live in order to get the nice snapshot below:

![image](https://cloud.githubusercontent.com/assets/578479/20165001/7f57ff68-a6d7-11e6-9e42-39fd72c223a8.png)

**Comment by DavidLGoldberg** [comment]
I'm on mac, el capitan

Sorry the create issue button gave me an error while trying to create with it this time.

**Comment by lee-dohm** [comment]
While this isn't an exact duplicate, the real solution here is to resolve #286 so that people don't have to enter a font by name anyway. Though I understand it wouldn't handle your specific case of wanting to specify a fallback font, you'll always have the ability to specify more complex styling via the `styles.less`.
