### ISSUE TITLE
keybinding suck!!

### ISSUE THREAD

**Issue by liron42** [atom/settings-view#882]
Please add an ability to change the keybinding from the keybinding screen...

I'm trying for more than an hour to change a simple key binding in atom : ctrl+shift+i
to the key binding: ctrl+shift+f 

As to what i read i need to change the coffee script and do all kind of crazy things for such a simple operation.. why?? a good text editor should enable the users to do simple operations like those with ease and not learn new language in order to change a simple key. 

I think there should be an ability to change the key from the keybinding screen without going into code..
from here: 
![image](https://cloud.githubusercontent.com/assets/18119833/20925047/36f725a0-bbbd-11e6-94ee-09b5bfda4a15.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused. In the future, if you want to send feedback to the maintainers you can do so more directly by sending email to atom@github.com.
