### ISSUE TITLE
Soft wrap doesn't work for files with long lines!

### ISSUE THREAD

**Issue by imalitavakoli** [atom/settings-view#930]
Soft wrap doesn't work well! e.g doesn't work for minfied .js or .css files... It won't get off or on!

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
