### ISSUE TITLE
When searching for a package to install, exact name is excluded from the list

### ISSUE THREAD

**Issue by felzix** [atom/settings-view#984]
_From @felzix on August 27, 2017 14:54_

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When searching for a package to install, using the package's exact name excludes that package from the list.

### Steps to Reproduce

1. Go to the `Install` tab in `Settings`.
2. Enter in, verbatim, `react`.

**Expected behavior:**
The `react` package is in the list of packages I could install. It should probable be the first one.

**Actual behavior:**

The `react` package isn't in the list at all. However, if I only enter in `reac` (less the `t`), the `react` package shows up.

<img width="846" alt="reac" src="https://user-images.githubusercontent.com/279660/29750902-d29f8a60-8afc-11e7-9ba7-40b5dbe61596.png">
<img width="889" alt="react" src="https://user-images.githubusercontent.com/279660/29750905-d60ef83e-8afc-11e7-9cc6-0bb2ae67aa11.png">

**Reproduces how often:** [What percentage of the time does it reproduce?]

always

### Versions
atom: 1.19.3
mac os sierra 10.12.6

_Copied from original issue: atom/atom#15464_

**Comment by felzix** [comment]
_From @Ben3eeE on August 28, 2017 5:58_

Thank you for reaching out!

This issue belongs in the [settings-view](https://github.com/atom/settings-view) repository. Can you please open the issue there if one does not already exist, thank you :bowing_man:

**Comment by jlvivero** [comment]
I believe this bug is not on the settings view but on apm itself.

When I run the command ./apm search "react" --json=true --packages=true > log.txt
(and after trimming the non important information) I get the following list:

[{"name":"re-re-re-react",
{"name":"react-builder",
{"name":"fancy-react",
{"name":"atom-react-mf-snippets",
{"name":"react-snippets",
{"name":"react-es6-snippets",
{"name":"react-es7-snippets",
{"name":"atom-react-intl-snippets",
{"name":"react-storybook-snippets",
{"name":"react-generatr",
{"name":"react-redux-react-native-snippets",
{"name":"react-function-to-class",
{"name":"react-tiny-snippets",
{"name":"fz-atom-react-snippet",
{"name":"bdd-react-snippets",
{"name":"react-redux-es6-snippets",
{"name":"react-snippets-for-atom",
{"name":"html-shorcuts-react",
{"name":"react-developer-snippets",
{"name":"atom-react-instyle",
{"name":"react-redux-es7-flow-snippets",
{"name":"react-native-snippets",
{"name":"react-redux-atom-snippets",
{"name":"react-esnext-snippets",
{"name":"modern-react-snippets",
{"name":"atom-react-snippets",
{"name":"atom-react-native-style",
{"name":"badass-react-snippets",
{"name":"react-component-preview",
{"name":"puddletown-react-snippets",


As you can see, there's no react package coming directly from apm (sorry for the bad formatting)

**Comment by jasonrudolph** [comment]
We've rolled out some improvements that should hopefully resolve this issue. I've included a couple before-and-after examples below.

I'm going to close this issue, but if you continue to observe problems searching for a package by exact name, please let us know.

## Atom UI

### Before

![image](https://user-images.githubusercontent.com/2988/34499831-ff9e93e2-efd5-11e7-8b32-702e7a2630fc.png)

### After

![image](https://user-images.githubusercontent.com/2988/34499840-05b023e0-efd6-11e7-84e5-6ab90bb00766.png)

## apm

### Before

```
$ apm search react --json=true --packages=true | jq ".[] | .name"
"re-re-re-react"
"atom-react"
"fancy-react"
"react-builder"
"react-snippets"
"react-redux-react-native-snippets"
"atom-react-mf-snippets"
"react-generatr"
"react-function-to-class"
"react"
"atom-react-intl-snippets"
"react-es6-snippets"
"react-es7-snippets"
"basic-react-snippets"
"fz-atom-react-snippet"
"bdd-react-snippets"
"html-shorcuts-react"
"react-tiny-snippets"
"react-snippets-for-atom"
"react-redux-es6-snippets"
"es6-react-redux-snippets"
"atom-react-instyle"
"atom-react-snippets"
"atom-react-native-style"
"react-redux-snippets"
"react-storybook-snippets"
"react-developer-snippets"
"modern-react-snippets"
"react-native-components"
"react-native-snippets"
```

### After

```
$ apm search react --json=true --packages=true | jq ".[] | .name"
"react"
"re-re-re-react"
"fancy-react"
"react-builder"
"react-snippets"
"react-redux-react-native-snippets"
"atom-react-mf-snippets"
"react-generatr"
"react-function-to-class"
"atom-react-intl-snippets"
"react-es6-snippets"
"react-es7-snippets"
"fz-atom-react-snippet"
"bdd-react-snippets"
"html-shorcuts-react"
"react-tiny-snippets"
"react-snippets-for-atom"
"react-redux-es6-snippets"
"atom-react-instyle"
"atom-react-snippets"
"atom-react-native-style"
"react-redux-snippets"
"react-storybook-snippets"
"react-developer-snippets"
"modern-react-snippets"
"react-native-components"
"react-native-snippets"
"react-native-snippets-horse"
"egghead-react-snippets"
"badass-react-snippets"
```
